Add a unit test with savings to the net worth function
loufranco/net-worth-estimator pull request #5
Opened 2023-04-25 17:51 UTC by Kocci4

2023-04-25 23:27 UTC, loufranco requested changes

2023-04-25 23:27 UTC, loufranco commented on python/lib/test_networth.py
> +        self.assertEqual(netWorthByAge([25, 26], 0.1, 10000, 40000, 0), [10000, 14600])
@Kocci4 I am making this comment so you see how to communicate in GitHub.  Please make another commit where you add a test to test a third year.

So, it would look like this

`self.assertEqual(netWorthByAge([25, 26, 27], 0.1, 10000, 40000, 0), [10000, 14600, XXX])`

I don't know what XXX is supposed to be, but you could try any number and the failed test will tell you what it expected.  I think it would be `14600 + (14600 * .06) + 4000`  First the market rate gets applied and then you save another 10%.

2023-04-25 23:27 UTC, loufranco commented on python/lib/test_networth.py
> +        self.assertEqual(netWorthByAge([25, 26], 0.1, 10000, 40000, 0), [10000, 14600])
If you end up with floating point error problems, you might need `assertAlmostEqual`, which you can only do with a single float (not an array).

So, it would be something like

```
nw = netWorthByAge([25, 26, 27], 0.1, 10000, 40000, 0)
self.assertAlmostEqual(nw[2], XXX.XXX, 3)
```

The `3` means 3 decimal places have to match.

2023-04-26 17:08 UTC, Kocci4 commented
@loufranco I have added the third unit test in order to test another age in the array.

I was able to implement the unit test without running into any floating point error problems, so everything should work fine comparing with integers.

2023-04-26 17:30 UTC, loufranco approved these changes

2023-04-26 17:30 UTC, merged